window.QUOTE_CATEGORIES = [
  { id: 13, name: "Épilation laser", short: "Laser", icon: "zap", tone: "mint" },
  { id: 32, name: "Microneedling · Mésothérapie · Peelings", short: "Peau & cheveux", icon: "sparkles", tone: "sand" },
  { id: 7, name: "Première consultation", short: "Consultations", icon: "user", tone: "blue" },
  { id: 16, name: "Traitements par injections", short: "Injections", icon: "aesthetic", tone: "rose" },
  { id: 17, name: "Traitements par laser", short: "Laser médical", icon: "scan", tone: "violet" },
  { id: 35, name: "Zones combinées · réservation par durée", short: "Zones combinées", icon: "zones", tone: "slate" },
  { id: 15, name: "Épilation électrique · électrolyse", short: "Électrolyse", icon: "electrolysis", tone: "amber" },
  { id: 9, name: "Médecine esthétique avec Dr. Poiraud", short: "Médecine esthétique", icon: "aesthetic", tone: "sand" },
  { id: 20, name: "Visage", short: "Visage", icon: "face", tone: "rose" },
  { id: 8, name: "Épilation définitive", short: "Épilation définitive", icon: "zap", tone: "mint" },
  { id: 21, name: "Poitrine et abdomen", short: "Poitrine & abdomen", icon: "torso", tone: "blue" },
  { id: 22, name: "Dos", short: "Dos", icon: "back", tone: "violet" },
  { id: 23, name: "Bras", short: "Bras", icon: "arms", tone: "mint" },
  { id: 24, name: "Maillot (zone intime)", short: "Maillot", icon: "maillot", tone: "rose" },
  { id: 25, name: "Jambes", short: "Jambes", icon: "legs", tone: "blue" },
  { id: 36, name: "Étudiant·e·s", short: "Étudiant·e·s", icon: "student", tone: "amber" }
];

const PRESTATION_VISUALS = {
  102: ["consultation", "Consultation d’épilation laser"],
  110: ["skin-target", "Zone cutanée à retoucher"],

  99: ["consultation", "Consultation du visage et de la peau"],
  96: ["scalp", "Cuir chevelu"],
  95: ["skin-target", "Visage ou zone cutanée du corps"],
  94: ["face-skin", "Peau du visage"],

  15: ["consultation", "Consultation de médecine esthétique"],
  14: ["consultation", "Consultation d’épilation définitive"],
  130: ["consultation", "Consultation du phototype cutané"],

  97: ["consultation", "Consultation pour injections"],
  63: ["injection-zone", "Zone du visage ou du corps à injecter"],
  100: ["injection-zone", "Zone injectée à retoucher"],
  87: ["forehead", "Haut du visage"],
  89: ["face-neck", "Visage et cou"],
  88: ["injection", "Zone du visage à restaurer"],
  93: ["face-skin", "Peau du visage"],
  90: ["nose", "Nez"],
  91: ["armpits", "Aisselles"],
  92: ["male-intimate", "Zone intime masculine"],

  98: ["consultation", "Consultation pour laser médical"],
  80: ["cheeks", "Joues et visage"],
  81: ["body-vessels", "Vaisseaux du corps"],

  111: ["zones", "Zones multiples du corps"],
  122: ["zones", "Zones multiples du corps"],
  123: ["zones", "Zones multiples du corps"],
  124: ["zones", "Zones multiples du corps"],
  125: ["zones", "Zones multiples du corps"],
  126: ["zones", "Zones multiples du corps"],
  127: ["zones", "Zones multiples du corps"],
  128: ["zones", "Zones multiples du corps"],
  129: ["zones", "Zones multiples du corps"],

  101: ["consultation", "Consultation d’électrolyse"],
  62: ["electrolysis", "Zone pileuse à traiter"],
  61: ["electrolysis", "Zone pileuse à traiter"],
  60: ["electrolysis", "Zone pileuse à traiter"],
  59: ["electrolysis", "Zone pileuse à traiter"],
  58: ["electrolysis", "Zone pileuse à traiter"],

  27: ["beard", "Barbe"],
  30: ["neck", "Cou"],
  22: ["glabella", "Entre les sourcils"],
  26: ["cheeks", "Joues"],
  19: ["upper-lip", "Lèvre supérieure"],
  28: ["beard-line", "Contour de la barbe"],
  20: ["chin", "Menton"],
  25: ["nose", "Nez et narines"],
  24: ["ears", "Oreilles"],
  21: ["eyebrows", "Sourcils"],
  23: ["temples", "Tempes"],
  29: ["face", "Visage complet"],
  109: ["face-zone", "Zone définie du visage"],

  33: ["abdomen", "Abdomen"],
  32: ["areola", "Aréoles"],
  34: ["linea-alba", "Ligne médiane de l’abdomen"],
  31: ["torso", "Torse (poitrine)"],
  108: ["torso-zone", "Zone définie de la poitrine ou de l’abdomen"],

  37: ["lower-back", "Bas du dos"],
  38: ["back", "Dos complet"],
  36: ["upper-back", "Haut du dos"],
  35: ["nape", "Nuque"],
  105: ["back-zone", "Zone définie du dos"],

  41: ["armpits", "Aisselles"],
  43: ["forearms", "Avant-bras"],
  44: ["arms", "Bras complets"],
  39: ["fingers", "Doigts"],
  42: ["shoulders", "Épaules"],
  40: ["hands", "Mains"],
  104: ["arm-zone", "Zone définie du bras"],

  45: ["bikini-classic", "Contour classique du maillot"],
  46: ["bikini-high", "Contour échancré du maillot"],
  47: ["maillot", "Maillot intégral"],
  48: ["male-intimate", "Zone intime masculine"],
  49: ["sif", "Sillon interfessier"],
  107: ["bikini-zone", "Zone définie du maillot"],

  54: ["thighs", "Cuisses"],
  56: ["lower-legs", "Demi-jambes, genoux et pieds"],
  55: ["buttocks", "Fesses"],
  52: ["knees", "Genoux"],
  57: ["legs", "Jambes et pieds complets"],
  50: ["toes", "Orteils"],
  51: ["feet", "Pieds"],
  106: ["leg-zone", "Zone définie de la jambe"],
  53: ["thigh-zone", "Zone définie de la cuisse"],

  112: ["student", "Zone du corps définie lors de la séance"],
  113: ["student", "Zone du corps définie lors de la séance"],
  114: ["student", "Zone du corps définie lors de la séance"],
  115: ["student", "Zone du corps définie lors de la séance"],
  116: ["student", "Zone du corps définie lors de la séance"],
  118: ["student", "Zone du corps définie lors de la séance"],
  119: ["student", "Zone du corps définie lors de la séance"],
  120: ["student", "Zone du corps définie lors de la séance"],
  121: ["student", "Zone du corps définie lors de la séance"]
};

const service = (id, name, price, duration, categoryId) => {
  const visual = PRESTATION_VISUALS[id];
  if (!visual) throw new Error(`Pictogramme de prestation manquant pour ${id} · ${name}`);
  return { id, name, price, duration, categoryId, icon: visual[0], zone: visual[1] };
};

window.QUOTE_FAMILIES = [
  { id: "visage", name: "Visage", description: "Lèvre, menton, joues, barbe et visage complet.", icon: "face", categoryIds: [20] },
  { id: "bras", name: "Bras & aisselles", description: "Aisselles, bras, avant-bras, épaules, mains et doigts.", icon: "arms", categoryIds: [23] },
  { id: "torse", name: "Torse & ventre", description: "Torse, abdomen, aréoles et ligne blanche.", icon: "torso", categoryIds: [21] },
  { id: "dos", name: "Dos & nuque", description: "Nuque, haut du dos, bas du dos et dos complet.", icon: "back", categoryIds: [22] },
  { id: "maillot", name: "Maillot", description: "Toutes les zones intimes et le SIF.", icon: "maillot", categoryIds: [24] },
  { id: "jambes", name: "Jambes & pieds", description: "Cuisses, demi-jambes, jambes complètes, genoux et pieds.", icon: "legs", categoryIds: [25] },
  { id: "electrolyse", name: "Électrolyse", description: "Épilation électrique facturée selon la durée.", icon: "electrolysis", categoryIds: [15] },
  { id: "medecine", name: "Médecine esthétique", description: "Injections, lasers médicaux, peau et cheveux.", icon: "aesthetic", categoryIds: [16, 17, 32] },
  { id: "combinees", name: "Zones combinées", description: "Réservations multi-zones organisées par durée.", icon: "zones", categoryIds: [35] },
  { id: "consultations", name: "Consultations", description: "Premiers rendez-vous, consultations et retouches.", icon: "consultation", categoryIds: [7, 13] },
  { id: "all", name: "Tous les soins", description: "L’ensemble des prestations disponibles.", icon: "all", categoryIds: [] }
];
window.QUOTE_SERVICES = [
  service(102, "Consultation offerte sans engagement", 0, 30, 13),
  service(110, "Retouche", 0, 15, 13),
  service(99, "Consultation avec Docteur Mickaël Poiraud", 100, 15, 32),
  service(96, "Mésothérapie capillaire", 280, 30, 32),
  service(95, "Microneedling / Mésothérapie", 280, 30, 32),
  service(94, "Peeling médical", 280, 30, 32),
  service(15, "Consultation en médecine esthétique avec le Dr. Mickael Poiraud", 100, 15, 7),
  service(14, "Consultation offerte pour l’épilation définitive", 0, 30, 7),
  service(130, "Consultation phototypes V et VI avec Dr. Poiraud", 100, 15, 7),
  service(97, "Consultation avec Docteur Mickaël Poiraud", 100, 15, 16),
  service(63, "Traitements par injections", 0, 30, 16),
  service(100, "Retouche injections", 0, 15, 16),
  service(87, "Toxine botulique", 420, 30, 16),
  service(89, "Injections Profhilo", 800, 30, 16),
  service(88, "Acide hyaluronique", 480, 30, 16),
  service(93, "Rejuran", 470, 30, 16),
  service(90, "Rhinoplastie", 620, 30, 16),
  service(91, "Hyperhydrose axillaire", 820, 30, 16),
  service(92, "Phalloplastie ou pénoplastie par injection", 820, 45, 16),
  service(98, "Consultation avec Docteur Mickaël Poiraud", 100, 15, 17),
  service(80, "Couperose du visage", 300, 30, 17),
  service(81, "Vaisseaux inesthétiques du corps", 300, 30, 17),
  service(111, "Réservation", 0, 15, 35),
  service(122, "Réservation", 0, 20, 35),
  service(123, "Réservation", 0, 30, 35),
  service(124, "Réservation", 0, 45, 35),
  service(125, "Réservation", 0, 60, 35),
  service(126, "Réservation", 0, 90, 35),
  service(127, "Réservation", 0, 120, 35),
  service(128, "Réservation", 0, 150, 35),
  service(129, "Réservation", 0, 180, 35),
  service(101, "Consultation offerte sans engagement", 0, 30, 15),
  service(62, "Moins de 15 minutes", 68, 15, 15),
  service(61, "15 minutes", 78, 20, 15),
  service(60, "30 minutes", 148, 35, 15),
  service(59, "45 minutes", 222, 50, 15),
  service(58, "60 minutes", 282, 70, 15),
  service(27, "Barbe", 222, 35, 20),
  service(30, "Cou", 122, 25, 20),
  service(22, "Entre-sourcils", 62, 15, 20),
  service(26, "Joues", 122, 30, 20),
  service(19, "Lèvre supérieure", 92, 20, 20),
  service(28, "Ligne de barbe", 222, 30, 20),
  service(20, "Menton", 92, 20, 20),
  service(25, "Nez et narines", 92, 20, 20),
  service(24, "Oreilles", 92, 20, 20),
  service(21, "Sourcils", 92, 20, 20),
  service(23, "Tempes", 92, 20, 20),
  service(29, "Visage complet", 322, 45, 20),
  service(109, "Zone spéciale 100 cm²", 99, 15, 20),
  service(33, "Abdomen", 222, 30, 21),
  service(32, "Aréoles", 92, 20, 21),
  service(34, "Ligne blanche", 62, 15, 21),
  service(31, "Torse", 222, 30, 21),
  service(108, "Zone spéciale 100 cm²", 99, 15, 21),
  service(37, "Bas du dos", 292, 35, 22),
  service(38, "Dos complet", 422, 60, 22),
  service(36, "Haut du dos", 292, 35, 22),
  service(35, "Nuque", 122, 25, 22),
  service(105, "Zone spéciale 100 cm²", 99, 15, 22),
  service(41, "Aisselles", 122, 15, 23),
  service(43, "Avant-bras", 222, 35, 23),
  service(44, "Bras complets", 322, 50, 23),
  service(39, "Doigts", 92, 15, 23),
  service(42, "Épaules", 222, 30, 23),
  service(40, "Mains", 122, 20, 23),
  service(104, "Zone spéciale 100 cm²", 99, 15, 23),
  service(45, "Maillot classique", 92, 20, 24),
  service(46, "Maillot échancré", 122, 25, 24),
  service(47, "Maillot intégral", 222, 30, 24),
  service(48, "Maillot masculin", 329, 40, 24),
  service(49, "SIF", 92, 15, 24),
  service(107, "Zone spéciale 100 cm²", 99, 15, 24),
  service(54, "Cuisses", 329, 45, 25),
  service(56, "Demi-jambes (genoux + pieds inclus)", 329, 40, 25),
  service(55, "Fesses", 292, 35, 25),
  service(52, "Genoux", 122, 15, 25),
  service(57, "Jambes complètes (pieds inclus)", 658, 70, 25),
  service(50, "Orteils", 62, 15, 25),
  service(51, "Pieds", 122, 15, 25),
  service(106, "Zone spéciale 100 cm²", 99, 15, 25),
  service(53, "Zones définies de la cuisse", 222, 30, 25),
  service(112, "Étudiant·e·s · 10 minutes", 0, 10, 36),
  service(113, "Étudiant·e·s · 15 minutes", 0, 15, 36),
  service(114, "Étudiant·e·s · 20 minutes", 0, 20, 36),
  service(115, "Étudiant·e·s · 30 minutes", 0, 30, 36),
  service(116, "Étudiant·e·s · 45 minutes", 0, 45, 36),
  service(118, "Étudiant·e·s · 60 minutes", 0, 60, 36),
  service(119, "Étudiant·e·s · 90 minutes", 0, 90, 36),
  service(120, "Étudiant·e·s · 120 minutes", 0, 120, 36),
  service(121, "Étudiant·e·s · 150 minutes", 0, 150, 36)
];
